package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
)

//export these 3 variables in your environment
var apiKey = os.Getenv("JIRATOKEN")
var company = os.Getenv("COMPANY")
var userEmail = os.Getenv("USEREMAIL")

func main() {
	req, err := http.NewRequest("GET", "https://"+company+".atlassian.net/rest/agile/latest/board/70", nil)
	if err != nil {
		log.Fatal(err)
	}
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	req.SetBasicAuth(userEmail, apiKey)
	req.Header.Set("Accept", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		// handle err
		log.Fatal(err)
	}
	defer resp.Body.Close()
	if err != nil {
		log.Fatal(err)
	}
	body, _ := ioutil.ReadAll(resp.Body)
	fmt.Println(string(body))
}
